GET http://localhost:5000/estudante HTTP/1.1
Content-Type: application/json

###

GET http://localhost:5000/estudante/1 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:5000/estudante/ HTTP/1.1
Content-Type: application/json

{
    "matricula_estudante": 2,
    "nome_estudante": "Messi da Silva",
    "email_estudante": "Ms@server.com"
}